# Generated by Django 3.0.2 on 2020-01-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbusername', models.CharField(max_length=100)),
                ('cbadminname', models.CharField(max_length=100)),
                ('cbmessage', models.TextField()),
                ('cbmsgbyuser', models.BooleanField(default=True)),
                ('cbtime', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
